slam_toolbox:
  ros__parameters:
    use_sim_time: true
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    mode: mapping
    minimum_time_interval: 0.1
    transform_publish_period: 0.02
    map_update_interval: 5.0
    resolution: 0.05
    min_laser_range: 0.35
    max_laser_range: 10.0
